logging:
  level:
    org:
      springframework: ERROR
    root: ERROR

server:
  port: 8090

spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
