logging:
  level:
    root: ERROR
    org: ERROR
    
spring:
   data:
    mongodb: 
      host: localhost
      port: 27017
      database: testdb

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
