logging:
  level:
    root: info
    org: info


spring:
   data:
    mongodb: 
      host: localhost
      port: 27017
      database: testdb
      
      
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/